# Cross compilation configuration

[target.aarch64-unknown-linux-gnu]
# Use pre-built Docker image with all dependencies
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

[target.aarch64-unknown-linux-gnu.env]
# Set environment variables for OpenSSL
passthrough = [
    "OPENSSL_STATIC",
]
volumes = []

# Enable static linking for OpenSSL to avoid runtime dependencies
[build]
default-target = "x86_64-unknown-linux-gnu"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
]